loomnetwork/dashboard

- src/components/FaucetHeader.vue
- src/components/chain-selector.ts
- src/services/initWeb3.js
- src/store/dappChainStore.js
- src/views/MyAccount.vue
- src/views/ValidatorDetail.vue
Adds a check that makes sure the user has mapped accounts before polling
Enables claim rewards flow on the delegate page
> Enable claim rewards

- src/components/Layout.vue
- src/store/dappChainStore.js
- src/views/MyAccount.vue
When changing accounts in metamask, make sure the corresponding "current" account variable in Vuex also gets updated.
> Update metamask account when switching accounts

- package.json
- yarn.lock
Fixes UI bug about updateAmount not being updated correctly because of https://github.com/loomnetwork/loom-js/pull/212
> bump loom to fix updateAmount bug

- src/components/FaucetHeader.vue
- src/components/Layout.vue
- src/components/chain-selector.ts
- src/components/modals/SuccessModal.vue
- src/router.js
- src/services/initWeb3.js
- src/store/dappChainStore.js
- src/store/dposStore.js
- src/views/FirstPage.vue
- src/views/MyAccount.vue
- src/views/Rewards.vue
- src/views/ValidatorDetail.vue
- src/views/ValidatorList.vue
Move dependency logic from router to mounted hook
Add logout event
Refine landing page
> Move dependency logic from router to mounted hook

- jenkins.sh
- src/components/FaucetHeader.vue
- src/components/FaucetSidebar.vue
- src/router.js
- src/store/dposStore.js
- src/views/BlockExplorer.vue
- src/views/FirstPage.vue
- src/views/Rewards.vue
- src/views/ValidatorDetail.vue
- src/views/ValidatorList.vue
Contains fixes for the following issues:
#21 
#22 
#26 
#31 
#10 
#28 
#32 
#27 
#23 
#25 
#24 
#30 
#33
> Fix bugs 21 - 33

- src/components/FaucetSidebar.vue
- src/components/Layout.vue
- src/components/modals/FaucetDelegateModal.vue
- src/router.js
- src/views/FirstPage.vue
- src/views/ValidatorDetail.vue
- Add new footer
- Show warnings when delegating or undelegating when previous delegation present.
- Redirect to login if user clicks on restricted links.
> New footer & Show warnings & Redirect to login

- src/components/LoadingSpinner.vue
- src/components/blockExplorer/block-list.ts
- src/views/MyAccount.vue
- src/views/Rewards.vue
- Fix block height
- Update copy on loading screen
- Enable logging for core operations
> Fix block height in block explorer and update copy

- src/store/applicationStore.js
- src/store/dappChainStore.js
- src/store/dposStore.js
- src/views/ValidatorDetail.vue
- Fix broken validator website link
- Make error prompts show longer
- Enable logging for all core calls
> Enable logging and fix link

- src/views/ValidatorDetail.vue
- Fixes links to website on the respective validator detail page
> Fix validator website links

- src/components/FaucetHeader.vue
- src/components/FaucetSidebar.vue
- src/store/dposStore.js
- src/views/Rewards.vue
- src/views/ValidatorList.vue
- Fix error handling when fetching validators
- Fix typos
> Fix error handling when fetching validators & fix typos

- src/components/FaucetTable.vue
- src/store/dappChainStore.js
- src/store/dposStore.js
- src/views/ValidatorDetail.vue
- src/views/ValidatorList.vue
Fix #68
Fix undefined reference to commit in getMetamaskLoomBalance
> Small fixes

- src/components/blockExplorer/BlockList.vue
- src/store/dposStore.js
- src/views/ValidatorDetail.vue
- yarn.lock
- Hide delegate buttons on prohibited nodes
- Fix arrow icons in blockexpore
> Quick fixes

- src/store/dappChainStore.js
- src/store/dposStore.js
- src/views/ValidatorDetail.vue
Make it more clear about which tokens are with/without bonuses
Builds on https://github.com/loomnetwork/dashboard/pull/111
> Remove hardcoded values and improve code for delegations

- src/components/FaucetHeader.vue
- src/components/Layout.vue
- src/components/WarningOverlay.vue
- src/views/FirstPage.vue
- src/views/MyAccount.vue
> Add login tabs

- src/components/modals/HardwareWalletModal.vue
- src/services/initWeb3.js
- src/services/ledger/paths.ts
- src/store/dappChainStore.js
using  correct derivation path
> Ledger paths

- src/components/modals/HardwareWalletModal.vue
HD paths for legacy addresses weren't set correctly. Fixed it by adding a check for legacy paths.
> Solved bug with legacy HD paths fixes #159

- src/components/FaucetHeader.vue
- src/components/modals/RestoreAccountModal.vue
> Security hotfix: turn off autocomplete and reload session

- src/components/modals/FaucetDelegateModal.vue
This solves #172 , since it makes the minimum that is able to be delegated (and un-delegated) zero.
> Added min=0 to input

- src/components/FaucetHeader.vue
- src/components/Layout.vue
- src/components/modals/HardwareWalletModal.vue
- src/store/dappChainStore.js
- src/store/dposStore.js
- src/views/FirstPage.vue
- src/views/MyAccount.vue
- show `unlock-ledger-modal` when user didn't unlock ledger
- show `sign-ledger-modal` when trying to sign mapping
- show  `already-mapped` when selected address already mapped
> First mapping

- src/components/modals/HardwareWalletModal.vue
> add support for showing up to 99 addresses

- src/components/modals/RestoreAccountModal.vue
- Currently the seed phrase does not do any validation on the checksum on seed phrase generated by the bip39 library.
> Validate seed phrase

- src/components/TransferStepper.vue
- src/store/dappChainStore.js
- src/views/MyAccount.vue
Display the allowance (amount approved but not deposited) under the ethereum balance, with a button to complete deposit
> Deposit allowance

- src/components/FaucetHeader.vue
> add manual refresh for balance

- src/components/modals/RedelegateModal.vue
- src/store/dposStore.js
- src/views/ValidatorDetail.vue
> properly call redelegate function and pass in correct parameters

- package.json
- src/components/TransferStepper.vue
- src/locales/en.json
- src/locales/es.json
- src/locales/ja.json
- src/locales/ko.json
- src/locales/th.json
- src/locales/zh.json
- src/store/dappChainStore.js
- src/views/MyAccount.vue
- yarn.lock
DONE
- check unclaimed tokens (deposit failed)
- button for reclaimed
- check pending withdrawal tokens (withdraw failed)
- button for withdraw pending tokens
IN PROGRESS
- Make it auto call check pending tokens after withdraw failed
- add localizations
> Fix loom tokens claiming

- src/views/ValidatorDetail.vue
> update delegate button state condition

- src/assets/ethereum-icon.svg
- src/components/FaucetSidebar.vue
- src/components/Layout.vue
- src/locales/en.json
- src/router.js
- src/store/dappChainStore.js
- src/store/dposStore.js
- src/views/History.vue
Add history page and store wallet type in store from local storage
> History page + store wallet type

- src/components/TransferStepper.vue
- src/store/dappChainStore.js
- src/views/MyAccount.vue
- do not detect pending withdrawal in normal withdraw flow
- do not let user continue withdraw if signature didn't get update from oracle yet  
- update withdraw tab immediately 
- fix resolve withdraw in  TransferStepper
> fix pending withdrawal 

- src/components/TransferStepper.vue
- src/store/dappChainStore.js
- src/store/dposStore.js
- src/views/MyAccount.vue
Disable all transfer related buttons when there"s an ongoing transfer process
- resume deposit
- deposit
- withdraw
- reclaim withdrawal
Add boolean state.dpos.gatewayBusy and have actions toggle it accordingly
> Manage busy gateway

- src/components/TransferStepper.vue
- src/store/dappChainStore.js
- src/views/MyAccount.vue
- some feedback on the amount form
- move int check to contract calls
> Amount input validation

- package.json
- src/store/dposPlugin.ts
- src/store/dposStore.js
- src/store/index.js
- src/views/MyAccount.vue
- yarn.lock
PS:
+1 dependency, rx to keep logic out of components, vuex watch/subscribe are used to trigger actions, this can be a start to a progressive refactoring, making components as dumb as possible, logic easier to write tests for.
> Daily withdrawal allowance

- src/store/dappChainStore.js
- src/views/MyAccount.vue
small withdraw bug + turn on oracle
> withdraw, commit is undefined

- src/views/ValidatorDetail.vue
Auto polling and adding a spinner
> improve delegation ux by using auto polling

- src/components/modals/HardwareWalletModal.vue
- src/services/initWeb3.js
This solves issue: #235 and further improves the user experience
- Implement pagination
- Implement flow using Ledger official APIs instead of MEW
- Simulate debounce on submit
* Add loading spinner
> Implement flow without MEW

- package.json
- src/contracts/Gateway.json
- src/contracts/LoomToken.json
- src/store/dappChainStore.js
- yarn.lock
New addresses and loom-js version for Asia1. Loom-js points to an open PR, but will be replaced witih new version once https://github.com/loomnetwork/loom-js/pull/231 is merged.
> Asia1 update for new gateway

- src/components/Layout.vue
- src/locales/en.json
Radical but should avoid problems like #260
> refresh page on metamask change of address.

- package.json
- src/contracts/Gateway.json
- src/contracts/LoomToken.json
- src/store/dappChainStore.js
- yarn.lock
Reverts loomnetwork/dashboard#263
> Revert "Asia1 update for new gateway"

- src/components/modals/RedelegateModal.vue
- src/views/MyDelegations.vue
- fix #245 
- link delegations in MyDelegations to ValidatorDetails
> Show spinner while redelegating

- src/components/modals/HardwareWalletModal.vue
- src/services/initWeb3.js
Reverts loomnetwork/dashboard#280
> Revert "hotfix: adds back support for 100 addresses"

- src/components/modals/HardwareWalletModal.vue
- src/services/initWeb3.js
Reverts loomnetwork/dashboard#281
> Revert "Revert "hotfix: adds back support for 100 addresses""

- package.json
- src/index.js
- src/views/ValidatorDetail.vue
- yarn.lock
- using moment duration format for time to unlock
- added missing value for `redelegating` in states enum
- hide updated amount if 0 (which is unnecessary when a delegation is bonded)
> Various fixes for Validator details page

- package.json
- public/index.html
- src/assets/scss/main.scss
- src/components/FaucetHeader.vue
- src/components/Layout.vue
- src/components/LoomIcon.vue
- src/index.js
- src/router.js
- src/store/dposStore.js
- src/views/MobileAccount.vue
- src/views/MyAccount.vue
- yarn.lock
> Mobile account

- src/components/FaucetHeader.vue
- src/components/Layout.vue
- src/router.js
- src/store/dposStore.js
- src/views/MobileHistory.vue
> Mobile history page

- src/views/FirstPage.vue
> Mobile homepage layout

- src/App.vue
added css to force dialogs width to mobile screen width
> force dialogs to fit mobile screen

- src/views/FirstPage.vue
- vue.config.js
minor fixes for im token
changes to vue config to work with ngrok by default
> Imtoken login fix

- src/App.vue
- src/assets/scss/main.scss
- src/components/FaucetFooter.vue
- src/components/FaucetHeader.vue
- src/components/Layout.vue
- src/components/modals/FaucetDelegateModal.vue
- src/components/modals/RedelegateDropdownTemplate.vue
- src/components/modals/RedelegateModal.vue
- src/filters.ts
- src/index.js
- src/store/dappChainStore.js
- src/store/dposPlugin.ts
- src/store/dposStore.js
- src/views/MobileAccount.vue
- src/views/MyDelegations.vue
- src/views/ValidatorDetail.vue
- src/views/ValidatorList.vue
**Do not merge until [#309](https://github.com/loomnetwork/dashboard/pull/309) is merged**
- mobile version of ValidatorDetails
- ValidatorDetails now shows multiple delegations if any
- no more delegations/validators refresh from ValidatorDetails component
- delegations are refreshed automatically after any delegation actions
> Mobile validator details

- src/components/FaucetHeader.vue
- src/components/Layout.vue
- src/components/TransferStepper.vue
- src/views/MobileAccount.vue
- src/views/MobileHistory.vue
> Add refresh balances and fix cosmetic issues

- src/components/modals/FaucetDelegateModal.vue
- src/store/dappChainStore.js
- src/store/dposStore.js
- src/views/ValidatorDetail.vue
- Fix smaller cosmetic issues and capture rewards error.
- Resolve sign in flow issues.
- Reinitialize client and address mapper
> Eth signing for new users

- package.json
- set_eth_addresses.sh
- src/store/dappChainStore.js
- Added a script that changes contract addresses values in the store, env vars:
`$LOOM_ADDRESS` and `$GW_ADDRESS`
- Re-enabled local in networks
> Local deployment hack

- src/views/MobileHistory.vue
Adds polling to the mobile history page.
> Add history polling

- src/components/FaucetHeader.vue
- src/components/HistoryEvent.vue
- src/components/TransferStepper.vue
- src/views/MobileAccount.vue
- src/views/MobileHistory.vue
- Await transaction confirmation before showing link to history page.
- Hide history page and account page if not logged in.
- Add separate component for history event.
> Await confirmation

- src/views/MyAccount.vue
> Fix resume deposit

- src/components/FaucetHeader.vue
- src/components/LangSwitcher.vue
- Add language switcher to mobile menu.
> Add language switcher

- .github/ISSUE_TEMPLATE/bug_report.md
- package.json
- set_eth_addresses.sh
- src/components/FaucetHeader.vue
- src/components/LangSwitcher.vue
- src/components/LoadingSpinner.vue
- src/components/modals/RedelegateModal.vue
- src/locales/es.json
- src/locales/ja.json
- src/locales/ko.json
- src/locales/th.json
- src/locales/zh.json
- src/store/dappChainStore.js
- src/store/dposStore.js
- src/views/FirstPage.vue
- src/views/MobileAccount.vue
- src/views/MyAccount.vue
- src/views/ValidatorDetail.vue
- Merge *develop* into *mobile-ui* branch and resolve conflicts.
- Edit bash script to reflect both Linux and OSX.
- Enable automatic login only if on mobile.
> Mobile ui merger

- src/components/modals/RedelegateModal.vue
- src/store/dappChainStore.js
- src/store/dposStore.js
set isBootsrap upon receiving the validators list (dappChainStore.getValidatorsAsync)
> set isBootsrap at the source (dappChainStore.getValidatorsAsync)

- src/views/MyAccount.vue
Fixes allowance/ resume deposit bug reported on support-plasmachain
> change this.allowance to this.currentAllowance

- src/components/Layout.vue
- src/components/TransferStepper.vue
- src/locales/en.json
- src/views/MobileAccount.vue
Fixed for issues related to IM wallet:
https://docs.google.com/spreadsheets/d/1Q_IwMDjl__N1uGuFRP1isCpAZQwKj-gzZ3yOrGe-Soo/edit#gid=0
> Fix imwallet issues

- src/utils.js
if the amount is between ]0,1[ show 9 decimals
> Show small crypto amounts

- src/components/FaucetHeader.vue
- src/components/FaucetSidebar.vue
- src/components/LangSwitcher.vue
- src/components/Layout.vue
- src/components/LoadingSpinner.vue
- src/components/LoomIcon.vue
- src/locales/en.json
- src/views/MobileAccount.vue
> Add sidebar, max-width and change modal to alert

- src/components/Layout.vue
> Friendlier notification

- src/components/gateway/DepositApproved.vue
- src/components/gateway/DepositConfirmed.vue
- Close deposit confirmed dialog on view confirmations click  #445 
- reset deposit approved state on close
- Close preceding popup before showing the next #444
> Fix deposit flow dialogs

- src/components/TransferStepper.vue
reset error list after setting amount all
> issue #477

- src/components/modals/RedelegateModal.vue
- src/store/dposStore.ts
- Fix call to relegate.
- Add missing index.
> Fix redelgation

- package.json
- src/store/dappChainStore.ts
- src/store/dposStore.ts
- yarn.lock
redundant since https://github.com/loomnetwork/loom-js/pull/266 and https://github.com/loomnetwork/go-loom/pull/370/files
Requires loom-js 1.51.1
> remove unused variable pubkey

- src/store/dappChainStore.js
- src/views/MobileAccount.vue
> Withdraw fixes dpos2

- src/store/dappChainStore.ts
- Chain Id should be state.currentChain.chainId
> Add fix for staking

- src/components/TransferStepper.vue
- src/components/modals/FaucetDelegateModal.vue
- src/store/dappChainStore.ts
- src/views/MobileAccount.vue
Setting gatewaysBusy to false in catch blocks
> Fix "gateway busy"

- src/store/dposPlugin.ts
watcher does not emit when the new value is the same as the old value
> electionTime fix

- src/store/dappChainStore.ts
- src/views/MobileAccount.vue
- Add button cooldown on *complete withdraw* button to prevent gas error.
- Set gatewayBusy as false when user rejects tx.
> Fix withdrawal issues

- src/components/TransferStepper.vue
- src/views/MobileAccount.vue
- Add polling to disable spinning animation.
> Add withdrawal polling

- src/views/ValidatorDetail.vue
- Disable staking for bootstrap validators.
- Enable consolidate.
> Add conditional check for bootstrap  validators

- src/views/ValidatorDetail.vue
> staging <- develop

- src/store/dposPlugin.ts
- 0 seconds means election running
- if election running just poll with a value between 1 and 120 seconds (here 15s)
> Simplified election time handling

- src/views/MobileAccount.vue
- spinner on pending dpos actions
- link myaccount/delegations to validator
> spinner on pending dpos actions

- src/store/dposPlugin.ts
- src/store/dposStore.ts
- src/views/MobileAccount.vue
Use window visibilityChange to retrigger election time loop.
> Fix election time refresh on tab visibility change

- package.json
- src/store/dappChainStore.ts
- src/store/dposStore.ts
- yarn.lock
Also use the check/claim rewards functions with improved UX
> Use GatewayVersion enum instead of raw number and bump loom-js

- package.json
- src/store/dposStore.ts
- Hotfix to fix limbo validator.
> Add fix for limbo validator

- src/components/AmountInput.vue
- src/components/InputAddress.vue
- src/components/modals/TransferTokensFormModal.vue
- src/views/DepositWithdraw.vue
- hide search if tokens less than 7
- fix inputAmount (All balance button)
- add inputAddress component to transferTokenModal component
> Search wallet

- src/utils.ts
utility function for get wallet from localstorage
- getWalletFromLocalStorage
- setNewTokenToLocalStorage
> Get wallet from localstorage

- src/config/production.ts
- src/config/stage.ts
- src/services/TokenService.ts
- src/store/index.ts
- src/views/DepositWithdraw.vue
- include tokens url in config
- setUrl app initialization
- cache tokens data on setUrl()
> cache tokens data on setUrl

- src/components/Account.vue
- src/components/game-asset/Cards.vue
- src/components/game-asset/Packs.vue
- src/components/modals/TransferAllCardsModal.vue
- src/components/modals/TransferCardsModal.vue
- src/components/modals/TransferPacksModal.vue
- src/config/dev.ts
- src/config/production.ts
- src/config/stage.ts
- src/filters.ts
- src/store/ethereum/index.ts
- src/store/ethereum/types.ts
- src/store/plasma/index.ts
- src/store/plasma/types.ts
> Fix assets issue

- src/components/gateway/WithdrawConfirmed.vue
- src/components/modals/AddTokenModal.vue
- src/components/modals/TransferTokensFormModal.vue
- src/config/stage.ts
- src/services/TokenService.ts
- src/store/ethereum/index.ts
- src/store/ethereum/types.ts
- src/store/gateway/ethereum.ts
- src/store/gateway/index.ts
- src/store/gateway/mapper.ts
- src/store/gateway/mutations.ts
- src/store/gateway/plasma.ts
- src/store/gateway/reactions.ts
- src/store/index.ts
- src/store/plasma/index.ts
- src/store/plasma/tokens.ts
- src/utils.ts
- src/views/DepositWithdraw.vue
Revisit token service 
Use token service for any address lookup
Fix amount in transfer
> Fix contracts loading

- src/locales/en.json
- src/store/whitelist/index.ts
- src/views/AddKey.vue
this should fix #677 #678 #679  #666 #674
> Handle deployer address already exists

- src/locales/en.json
> Fix success message

- src/components/gateway/WithdrawConfirmed.vue
- src/components/gateway/WithdrawForm.vue
- src/store/ethereum/index.ts
- src/store/ethereum/mutations.ts
- src/store/ethereum/reactions.ts
- src/store/ethereum/types.ts
- src/store/gateway/ethereum.ts
- src/store/gateway/plasma.ts
- src/store/gateway/reactions.ts
- src/views/DepositWithdraw.vue
Handle receipt scenarios (unclaimed withdraw &  timeout when claimed withdrawal)
> New withdrawal flow

- src/components/InputAddress.vue
> Lighten `InputAddress` placeholder color

- src/views/AddKey.vue
> Fix issue #673

- src/components/FaucetHeader.vue
- src/components/Layout.vue
- src/components/modals/SeedPhraseModal.vue
- src/feedback/components/FeedbackNotification.vue
> Fix `Copied to clipboard` notification is missing

- src/views/AddKey.vue
> Reset address to empty after adding the key

- src/components/game-asset/Cards.vue
> capitalize total-amount

- src/components/FaucetSidebar.vue
- src/components/gateway/DepositForm.vue
- src/components/modals/TransferTokensFormModal.vue
- src/store/plasma/index.ts
- src/store/plasma/mutations.ts
- src/views/DepositWithdraw.vue
- fix transferTokenModal component
- remove mutation setSelectedToken
> fix all (balance) button on transferTokenModal

- src/views/DepositWithdraw.vue
- src/whitelist/views/AddKey.vue
this will redirect to Deposit/Withdraw page and triggered deposit modal
> Fix deposit link on addkey

- src/components/InputAddress.vue
- src/components/modals/SeedPhraseModal.vue
- src/store/plasma/index.ts
- src/whitelist/store/index.ts
- src/whitelist/views/AddKey.vue
- hash 64 bytes instead of mnemonic
- make input address field optional {loom | 0x}
- refresh deployer list after added key
- don't check address if it's a empty string
> Update dev deploy page

- src/components/Account.vue
> Fix wrong loom address is getting copied

- package.json
- src/components/gateway/DepositForm.vue
- src/components/gateway/WithdrawForm.vue
- src/dpos/components/DelegateModal.vue
- yarn.lock
- Bump loom.
- Add user's token balance on deposit & withdraw modals.
- Change to show stake rewards in percentage form.
> Bump loom, token balance and stake rewards in percentage form

- src/components/InputAddress.vue
> Reset address value to empty after adding new key

- src/components/FaucetHeader.vue
- src/feedback/components/LoadingBar.vue
- src/feedback/store/index.ts
- src/feedback/store/mutations.ts
- src/feedback/store/types.ts
- src/locales/en.json
- src/store/gateway/ethereum.ts
- Add loading bar component to deposit flow.
> Add loading bar

- src/components/modals/TransferCardsModal.vue
> Transfer max amount for a particular card

- src/App.vue
> Transform text button to capitalize

- src/dpos/views/ValidatorList.vue
help the user to know any item in the table can click to see more detail
> Validator list page : UI Improvement

- src/dpos/components/RedelegateModal.vue
- src/dpos/store/index.ts
- check bootstrap validators while parsing candidates response
- Fix null error when no redelegation is requested
> Minor fixes

- src/dpos/components/RedelegateModal.vue
Lazy modal binding on vue-bootstrap does not seem to help
> Fix null error when no redelegation is requested

- src/dpos/components/Rewards.vue
- src/dpos/store/helpers.ts
- src/dpos/store/index.ts
- src/dpos/store/types.ts
> Rewards are only claimed after the next election 

- src/components/gateway/WithdrawForm.vue
> Add space between buttons

- src/store/ethereum/index.ts
- src/store/ethereum/types.ts
- src/store/gateway/plasma.ts
We were using a hard coded us1 address in the withdraw function.
> Remove erc20Addresses, use tokenService

- src/components/HistoryEvent.vue
History: Tx links from history page is not taking us to anywhere #814
> Fix tx link (history page)

- src/store/gateway/index.ts
- src/store/gateway/mapper.ts
- src/store/gateway/mutations.ts
- src/store/gateway/reactions.ts
- src/store/gateway/types.ts
- src/views/FirstPage.vue
URL for checking mapping only usable in
https://stage-auth.loom.games/wallet/address?address=[address]&wallet=eth
because dev-auth.loom.games always return valid_address = true, whatever address is
> Check address mapping if user come from marketplace 

- src/components/gateway/DepositForm.vue
- src/components/gateway/WithdrawConfirmed.vue
- src/components/gateway/WithdrawForm.vue
- src/store/gateway/binance.ts
- src/store/gateway/ethereum.ts
- src/store/gateway/index.ts
- src/store/gateway/mapper.ts
- src/store/gateway/mutations.ts
- src/store/gateway/plasma.ts
- src/store/gateway/reactions.ts
- src/store/gateway/types.ts
- src/store/plasma/tokens.ts
- src/views/FirstPage.vue
- fix plasma approval in withdraw
- ERC20 withdraw
- ETH withdraw
Known issues:
- default metamask gas price for ETH transfers is always insufficient
- ETH: multisig failing ( most likely createWithdrawalHash values)
> Fix gateway other coins

- src/locales/en.json
> Update event name

- src/dpos/store/__test__/mutations.spec.ts
- src/dpos/store/mutations.ts
> DPoS store - Mutations test

- src/dpos/components/DelegateModal.vue
- src/dpos/store/index.ts
- src/dpos/store/types.ts
- src/dpos/views/ValidatorList.vue
- fix display of total stakes
- fix delegate modal button state
- 3 months tier is 7.5
- display correct amount input error state
> Dpos fixes

- src/feedback/components/FeedbackNotification.vue
> Remove timeouts on alerts

- src/dpos/views/ValidatorList.vue
> Fix total staked sorting to sort properly

- src/dpos/views/ValidatorList.vue
> ignore bootstrap nodes, from locked token totals

- src/store/ethereum/index.ts
- src/store/ethereum/reactions.ts
- src/store/ethereum/types.ts
Until we switch to web socket provider.
See #872
> Avoid using  eth_subscribe

- src/components/ChainSelector.vue
- src/components/FaucetHeader.vue
- src/index.ts
- src/store/index.ts
Move config initialisation to app beforeMount
> Fix token contract race

- public/index.html
- also removed useless CSS code
- removed segment because we are no longer use it
> add twitter & facebook trakcing code

- src/store/gateway/ethereum.ts
> Fix missing localize string

- src/components/FaucetSidebar.vue
- src/dpos/components/ValidatorExtendedDetail.vue
- src/dpos/components/ValidatorRewards.vue
- src/dpos/views/ValidatorManagement.vue
- src/router.ts
with validator detail component & validator rewards
> Validator management page

- src/components/AmountInput.vue
- src/utils.ts
just on a AmountInput.vue & utils.ts. that's it, right?
> Fix token formatter, allow custom exponent #940

- src/components/modals/AddTokenModal.vue
> Change to virtual list component

- src/components/gateway/DepositBinance.vue
> Fix deposit binance modal typo

- src/components/gateway/DepositBinance.vue
> Fix deposit binance link to open in new tab

- src/components/gateway/DepositBinance.vue
> Fix deposit binance close button is not working

- src/components/gateway/DepositBinance.vue
- src/services/TokenService.ts
- src/services/__test__/tokenService.spec.ts
Temporarily hard code binance gateway account in tokenService
> #976 Binance gateway account

- src/components/HistoryEvent.vue
- src/components/LoadingSpinner.vue
- src/dpos/views/ValidatorDetail.vue
- src/store/ethereum/index.ts
- src/store/ethereum/reactions.ts
- src/store/gateway/ethereum.ts
- src/store/plasma/index.ts
- src/views/MobileHistory.vue
- vue.config.js
- Use await calls to fetch history
- Wait for blocknumber
> Fix history page

- src/components/HistoryEvent.vue
- src/components/LoadingSpinner.vue
- src/components/modals/AddTokenModal.vue
- src/dpos/store/index.ts
- src/dpos/views/ValidatorDetail.vue
- src/dpos/views/ValidatorList.vue
- src/store/ethereum/index.ts
- src/store/ethereum/reactions.ts
- src/store/gateway/ethereum.ts
- src/store/plasma/index.ts
- src/views/MobileHistory.vue
- Validator Sorting
- History page fixes
- Add token, token list not appearing on mobile
> Staging > Master hot fixes

- src/views/DepositWithdraw.vue
> Check if selected token is available for binance #980

- src/App.vue
- src/components/FaucetHeader.vue
- src/views/DepositWithdraw.vue
- Poll token balances every 15 seconds.
- Add button to manually refresh.
> Add refresh token balance

- src/contracts/MigratedZBGCard.json
> #663 Change contract address to new one for staging

- src/dpos/components/RegisterCandidateForm.vue
- src/dpos/components/ValidatorExtendedDetail.vue
- src/dpos/store/__test__/_helpers.ts
- src/dpos/store/__test__/candidate.spec.ts
- src/dpos/store/__test__/delegate.spec.ts
- src/dpos/store/index.ts
- src/feedback/components/FeedbackNotification.vue
- src/store/ethereum/wallets/ledger.ts
> Add registerCandidate

- src/components/ChainSelector.vue
- src/components/FaucetSidebar.vue
- src/config/dev.ts
- src/config/local.ts
- src/config/production.ts
- src/config/stage.ts
- src/dpos/components/RegisterCandidateForm.vue
- src/dpos/components/ValidatorExtendedDetail.vue
- src/dpos/store/__test__/_helpers.ts
- src/dpos/store/__test__/candidate.spec.ts
- src/dpos/store/__test__/delegate.spec.ts
- src/dpos/store/index.ts
- src/feedback/components/FeedbackNotification.vue
- src/router.ts
- src/store/ethereum/wallets/ledger.ts
- src/store/gateway/index.ts
- src/store/gateway/types.ts
- src/views/FirstPage.vue
- src/views/TransferGateway.vue
> Token mappings #763

- package.json
- src/assets/scss/main.scss
- src/config/ext-dev.ts
- src/index.ts
- vue.config.js
- yarn.lock
Making sure we only include one copy of bn drops the bundle size by 1.5 MB.
Same can be done for web3 submodules
> Webpack: alias bn

- src/dpos/components/ValidatorExtendedDetail.vue
- src/views/TransferGateway.vue
#1020 & change 'not found' message in transfer gateway page
> Delete total staked in validator page

- src/components/InputAddress.vue
> Binance addresses on prod have prefix bnb

- src/views/TransferGateway.vue
1. on view logs => 'LOOM' will equal 'LOOMCOIN
2. add 'token not found' message
> Update transfer gateway page

- src/views/DepositWithdraw.vue
This reverts commit eaf0f81e8866d6e7684025d75d0656b192dd7bf7.
> Re-enable BNB transfers

- src/components/gateway/WithdrawForm.vue
- src/store/gateway/index.ts
- src/store/gateway/plasma.ts
- Edit wrong property name.
- Change conditional when detecting past transactions.
> Fix continuous withdrawals

- src/components/modals/HardwareWalletModal.vue
- src/views/FirstPage.vue
- src/views/MobileAccount.vue
- src/views/TransferGateway.vue
also fix input form on transfer gateway page
> Message on deprecated Ledger (legacy)

- src/components/FaucetSidebar.vue
- src/config/dev.ts
- src/config/ext-dev.ts
- src/config/local.ts
- src/config/production.ts
- src/config/stage.ts
- src/dpos/store/__test__/mutations.spec.ts
- src/dpos/store/helpers.ts
- src/dpos/store/index.ts
- src/dpos/store/mutations.ts
- src/dpos/store/types.ts
- src/router.ts
- src/store/index.ts
- src/views/Analytics.vue
> Bring back analytics

- src/dpos/views/ValidatorList.vue
> Improve UI for validator page

- src/components/MappedTokenAddress.vue
- src/services/TokenService.ts
- src/views/TransferGateway.vue
- Add tabs in transfer gateway page
- adjust an ui to look more okay
- fix a token symbol bug ( return real data object it cause bug so change it to return copied one instead )
- remove mockup 'loom' token address
> #1059 #1075 Add tabs in gateway page

- package.json
- scripts/ERC20_frag.json
- scripts/gen-tokens-info.ts
- scripts/production.json
- scripts/stage.json
- src/components/AmountInput.vue
- src/dpos/views/ValidatorList.vue
- Fix undelegate all
- recently missed blocks typo
> Staging < develop

- src/locales/en.json
- src/store/gateway/ethereum.ts
> History: Support multiple tokens

- src/store/ethereum/getters.ts
- src/store/ethereum/index.ts
- src/store/ethereum/mutations.ts
- src/store/ethereum/reactions.ts
- src/store/ethereum/types.ts
- src/store/gateway/ethereum.ts
- src/store/gateway/index.ts
> User local storage

- src/store/gateway/ethereum.ts
- src/store/gateway/index.ts
- src/store/gateway/reactions.ts
> Refactor receipt checking 

- src/locales/en.json
- src/store/ethereum/index.ts
- src/store/ethereum/mutations.ts
- src/store/gateway/ethereum.ts
> Fix duplicate events + Add missing event names

- src/locales/en.json
- src/store/ethereum/reactions.ts
- src/store/gateway/ethereum.ts
- src/store/gateway/index.ts
> Check eth deposit if out of gas and prompt user

- src/store/gateway/index.ts
- Increase block number threshold to 20.
- Remove unused method.
> Remove unused method and increase blocknumber

- src/dpos/components/RegisterCandidateForm.vue
- src/dpos/components/ValidatorExtendedDetail.vue
- src/locales/en.json
- add ui & function to check on user balance to equal a required 1.25M tokens otherwise register form will be disabled
> Update register candidate form ui

- src/components/FaucetHeader.vue
- src/locales/en.json
- src/views/StakingGuide.vue
Fix typos, add mobile nav link and style images
> Staking Guide feedback & fixes

- package.json
- src/locales/en.json
- src/store/ethereum/index.ts
- src/store/ethereum/types.ts
- src/store/ethereum/wallets/walletconnect.ts
- src/views/FirstPage.vue
- src/whitelist/store/__test__/actions.spec.ts
- yarn.lock
> Add and initialize WalletConnect

- src/views/FirstPage.vue
fix when user redirect from another page to my account
#1198
> Fix announcement area not displaying

- package.json
- src/config/ext-dev.ts
- yarn.lock
> Update extdev gateways/multisig

- src/index.ts
> Add Sentry dedupe to lower the number of duplicates reported

- src/config/production.ts
- src/dpos/store/helpers.ts
+ enhance "former validator" label
> Use WS for default ethereum provider

- src/data/bountyList.json
- src/locales/en.json
- src/store/ethereum/index.ts
> Port back bounty fixes to develop

- package.json
- src/assets/tokens/dev.tokens.json
- src/assets/tokens/ext-dev.tokens.json
- src/components/gateway/WithdrawConfirmed.vue
- src/store/gateway/binance.ts
- src/store/gateway/ethereum.ts
- src/store/gateway/plasma.ts
- src/views/DepositWithdraw.vue
- yarn.lock
> make loom token can associate with binance chain

- src/config/production.ts
Enable multisig in production config
> multisig for production

- src/dpos/store/index.ts
- src/dpos/store/types.ts
- src/locales/en.json
> DPOS.claimDelegatorRewardsAsync only claim rewards from currently active validators. Will have to use DPOS.unbondAsync for each inactive validator to claim those rewards.
> Use unbond to claim past validator rewards

- src/locales/en.json
- src/locales/es.json
- src/locales/ja.json
- src/locales/ko.json
- src/locales/th.json
- src/locales/zh.json
- src/views/FeedbackForm.vue
Signed-off-by: Andrei Popescu <andrei.popescu@gmail.com>
> Replace Freshdesk with email link

- src/components/Layout.vue
- src/dpos/store/index.ts
- src/index.ts
- src/store/ethereum/reactions.ts
- src/utils.ts
> MetaMask Provider Migration

- src/components/Layout.vue
- src/dpos/store/index.ts
- src/index.ts
- src/store/ethereum/reactions.ts
- src/utils.ts
Remove unused code and tweak the way MetaMask is detected.
See https://docs.metamask.io/guide/provider-migration.html for context.
Co-authored-by: Vadim Macagon <vadim.macagon@gmail.com>
> MetaMask Provider Migration (#1377)

- src/config/dev.ts
- src/config/ext-dev.ts
- src/config/local.ts
- src/store/gateway/mapper.ts
That service is no longer operational.
> Don't try to query dev-auth.loom.games anymore

- src/locales/en.json
- src/locales/es.json
- src/locales/ja.json
- src/locales/ko.json
- src/locales/th.json
- src/locales/zh.json
- src/store/gateway/ethereum.ts
- src/views/DepositWithdraw.vue
We'll need to temporarily disable LOOM deposit/withdraw while upgrading Basechain infra to the new LOOM token.
> Disable LOOM deposit/withdraw buttons on Wallet page

- src/locales/en.json
- src/locales/es.json
- src/locales/ja.json
- src/locales/ko.json
- src/locales/th.json
- src/locales/zh.json
- src/store/gateway/ethereum.ts
- src/views/MobileHistory.vue
This issue only shows up on BSC Mainnet.
> Events should be queried from BSC in block ranges of no more than 5000 blocks
