loomnetwork/dashboard

src/components/modals/HardwareWalletModal.vue
Although it seems we a have fixed the address selection on ledger, adding this little sanity check might avoid unexpected behaviour.
=> assert we have the right account when initialising web3

src/views/MyDelegations.vue, src/views/ValidatorDetail.vue
Let people who delegated to bootstrap nodes before, re-delegate their tokens.
moved conditions out of template and made the buttons look different from each other
=> Redelegate on bootstrap validators 267

src/views/ValidatorDetail.vue
for delegations in "pending" state we should also check updateAmount (ie. redelegation)
=> hasDelegation = either amount > 0 or updateAmount > 0

src/assets/scss/main.scss, src/components/FaucetHeader.vue, src/components/Layout.vue, src/store/dappChainStore.js, src/store/dposPlugin.ts, src/store/dposStore.js, src/views/MobileAccount.vue, src/views/ValidatorList.vue
- election time is now automatically tracked as soon as dposUser is available (Vuex.watch)
- candidates/validators are automatically refreshed, once per election cycle (maybe we could schedule more refreshes for safety) (Vuex.watch)
Which leads to:
- `DPOS/getTimeUntilElectionsAsync` should no more be called from components. Instead components can read the already available `state.DPOS.timeUntilElectionCycle` (seconds) and the new `state.DPOS.nextElectionTime` (timestamp millis)
- `DappChain/getValidatorsAsync` should no more be called from components (unless it is for a manual refresh button) 
the validators page might still need a little aesthetic tuning...
=> Mobile Validators page and optimize dpos store

src/views/ValidatorDetail.vue
Addresses now show under validator name starting with plasma instead of 0x
=> Show the validator address but in a plasma format #424

src/store/dappChainStore.js, src/store/dposPlugin.ts, src/store/dposStore.js, src/views/MobileAccount.vue
- getTimeUntilElection and getValidators call store.getDpos2()
-  store.getDpos2() returns dposUser.dappchainDpos if dposUser is present create client and dpos contract if not
- vuex plugin trigger getTimeUntilElection immediately on start up.
- account view mount() waits for dposUser if not set
=> DPoS reports without dposUser

src/store/dposStore.js
Lock added the ability to sort events. So this should fix the history page.
=> Plasma history reverse chronological order

src/components/FaucetSidebar.vue, src/components/Rewards.vue, src/locales/en.json, src/router.js, src/store/dposStore.ts, src/views/MobileAccount.vue
- Remove *my delegations* page (as delegations are shown on account page).
- Remove rewards, and make it a component on the account page.
- Add loading spinners on account balance on account page.
=> Remove pages and combine rewards

src/components/modals/RedelegateModal.vue
- Clears redelegate modal when closed.
- Makes it possible to redelegate without selecting a target delegation.
- Clear error messages.
=> Fixes for issues 508, 506, 440, partaking to "Redelegation"

src/components/modals/RedelegateModal.vue
- Remove call to get target delegations.
- Remove UI to display target delegations.
- Send index of currently selected delegation (from origin validator).
=> Remove target delegation list and send selected delegation as index

src/views/ValidatorDetail.vue
If timestamp === 0, do not convert it to a date.
=> Quickfix for 0 timestamp

src/store/gateway/ethereum.ts
Debug validator signatures and remove unnecessary function parameters in the case of ETH when generating hash.
=> Generate correct hash for eth withdrawals.

package.json, src/dpos/components/Rewards.vue, src/services/TokenService.ts, src/services/__test__/tokenService.spec.ts, src/views/DepositWithdraw.vue
A few users had withdrawals of BNB to Ethereum stuck in the gateway after we migrated to BNB on Binance. This would allow them to complete their withdrawal to Ethereum. 
Should be removed once no old BNB receipts are stuck on the Ethereum gateway
=> Temporary: renable BNB on ethereum

src/dpos/store/index.ts, src/store/plasma/index.ts
Address arguments are not recovered. Only caller is mapped/recovered (#1155)
=> Hotfix: Limbo rewards

src/config/production.ts, src/store/gateway/reactions.ts
Disabling verification of ongoing withdrawals on ethereum side. Which we do in case a receipt is present. The check is used to avoid sending an other withdrawal request in case one is still unconfirmed on ethereum. The worse that could happen is the second tx failing. Which is fine.
=> Temporarily disable on going ethereum withdrawals check

src/components/gateway/WithdrawForm.vue, src/utils.ts
Withdrawal limits can be enforced on-chain, there's no longer any need to hardcode the limits in the UI.
=> Remove the hardcoded withdrawal limits

jenkins.sh
`wallet.loomx.io` now hosts the new dashboard, this one will only be deployed to `dashboard.dappchains.com` from now on.
=> Don't deploy to wallet.loomx.io anymore

scripts/ext-dev.json, src/assets/tokens/ext-dev.tokens.json
There's some code that assumes the contract addresses are all lowercase, the mixed case used previously caused a few errors.
=> Update LOOM token address on Rinkeby again

src/dpos/components/RegisterCandidateForm.vue, src/filters.ts
The problem here was that when the LOOM balance is 1000 or over `formatTokenAmount` returns a string with comma(s) (e.g. "1,000") and the comma(s) trip up the `BigNumber` constructor which then returns a `NaN`.
=> Fix NaN LOOM balance on validator registration form

src/config/dev.ts, src/config/ext-dev.ts, src/config/local.ts, src/config/production.ts, src/store/ethereum/index.ts, src/store/ethereum/types.ts, src/store/gateway/ethereum.ts, src/store/gateway/index.ts, src/store/gateway/reactions.ts, src/store/gateway/types.ts
Previously the gateway versions were assumed to be the same for BSC and Ethereum, but that's not true in some environments. Now the gateway versions must be set for BSC and Ethereum separately.
=> Configure gateway versions for each foreign network

package.json, yarn.lock
This fixes an issue with fetching info for newly registered validators from the chain.
=> Upgrade to loom-js@1.75.3

src/components/Layout.vue, src/store/ethereum/index.ts, src/store/ethereum/types.ts, src/store/ethereum/wallets/binance.ts, src/store/ethereum/wallets/metamask.ts, src/store/ethereum/wallets/walletconnect.ts
Currently if the user connects to the dashboard using WalletConnect then signing out doesn't disconnect the session, this makes it hard to recover from certain situations where a user gets stuck half-way through a deposit/withdrawal because they accidentally dismissed a WalletConnect request to sign a tx on their phone. There's a `disconnect` function on the WalletConnect provider that should be called when the user signs out.
=> Signing out should disconnect WalletConnect session

src/components/Layout.vue, src/store/gateway/mapper.ts, src/views/Analytics.vue
Currently we display a warning at the top of the dashboard if the user has MetaMask connected to a different network than we expect, this should also be caught and prevented on login, don't let the user sign in with MetaMask until they select the correct network.
=> Don't allow sign in with MetaMask if it's connected to the wrong network

src/assets/tokens/ext-dev.binance.tokens.json, src/config/ext-dev.ts
Reusing the same LOOM BEP20 token contract for `extdev` that was previously deployed to `asia1`.
=> Set Extdev LOOM Gateway address on BSC Testnet and enable BSC wallets

src/dpos/views/ValidatorDetail.vue
Login, go to the validator list, select a validator. On the validator details page the Stake button will at first appear right under the validator details, but then it'll jump to the bottom of the page causing the vertical scrollbar to appear.
Need to fix this jumping, the stake button should just stay directly under the validator details section, it should be jumping around.
=> Stake button always gets pushed off the bottom of the page

src/components/ChainSelector.vue
There was a `features.bscWallets` setting added to the config in this PR https://github.com/loomnetwork/dashboard/pull/1423
Unfortunately it doesn't look like switching the configuration on the login page has an immediate effect on this particular setting. For example if the dashboard is initially loaded with the `production` config selected then only the Ethereum wallets will be visible initially (`bscWallets === false`), if you then select `dev` from the drop-down the BSC wallets should be displayed immediately... but they do not appear until the page is reloaded.
=> Some config changes don't take effect until page reload

src/store/ethereum/index.ts, src/store/ethereum/wallets/binance.ts, src/store/gateway/ethereum.ts
The Binance Chain wallet API mimics MetaMask but has some quirks with the `personal_sign` web3 function we rely on for account mappings, specifically it doesn't implement `personal_sign` and instead provides a custom `bnbSign` function on the wallet instance. The problem is loom-js relies on an ethers.js signer that wraps the web3 provider, ethers.js doesn't know anything about this `bnbSign` function so it doesn't work with Binance Chain wallet. The quickest way to work around this is probably by monkey patching the ethers.js signer to call `bnbSign` instead of `personal_sign`.
=> Add support for Binance Chain wallet

src/components/gateway/WithdrawConfirmed.vue, src/feedback/components/FeedbackAlert.vue, src/locales/en.json, src/locales/es.json, src/locales/ja.json, src/locales/th.json
Clicking outside this dialog makes it disappear, leaving a withdrawal half-done, bad UX.
=> Withdrawal confirmation dialog shouldn't close on focus loss

src/locales/en.json, src/locales/es.json, src/locales/ja.json, src/locales/ko.json, src/locales/th.json, src/locales/zh.json
This dialog that pops up when the user attempts to login while their wallet is connected to a different network than expected should say:
`Your wallet is currently connected to X. Please connect it to Y, and then press the button below.`
That way the page reload is more likely to happen after they fix their wallet.
=> Make the "wrong network" dialog a bit clearer

src/store/plasma/reactions.ts
**Describe the bug**
ETH is showing up in the Basechain wallet when connected to BSC
**To Reproduce**
Steps to reproduce the behavior:
1. Go to https://dev-dashboard.dappchains.com
2. Connect to BSC Testnet
**Screenshots**
**Environment:**
- Chrome/Metamask
**Additional context**
0x2e8d2AA6AD610a111dB872F344D90B6a650A80de
=> ETH is showing up in the Basechain wallet when connected to BSC

.github/workflows/main.yaml
PR builds use Travis CI, which is basically dead now, so we need to switch to Github Actions.
=> Switch PR builds to Github Actions

src/components/WalletsTooltipsBSC.vue, src/components/WalletsTooltipsEthereum.vue, src/views/FirstPage.vue
The BSC wallets have useful tooltips when you mouse over them. The Ethereum wallets should have some too. Can copy MetaMask and WalletConnect tooltips from the BSC wallets. And the one for WalletLink should just make it obvious you need the Coinbase mobile wallet to use it.
=> Add tooltips for Ethereum wallets on the login page

src/components/LoadingSpinner.vue, src/dpos/views/ValidatorList.vue, src/locales/en.json, src/locales/es.json, src/locales/ja.json, src/locales/ko.json, src/locales/th.json, src/locales/zh.json
The `/validators` page should show some kind of loading indicator while the validator data is being fetched, right now on first load you just get a blank page for a while with no idea of what if anything is going on. And if the loading doesn't finish within a few seconds display a message that says "Oops, this is taking a bit longer than expected!" and a button that says "Try again".
=> Add a loading indicator to the validator list page

src/store/ethereum/index.ts, src/store/ethereum/wallets/walletconnect.ts
Here's an example scenario:
1. User selects WalletConnect from the login page, scans QR code to connect
2. User reloads the dashboard
3. User selects WalletConnect from the login page, is automatically connected because the previous session was reused
Reusing the session in step 3 can be confusing, the user might want to use a different account but they're automatically connected using the previous account. I think it's best to always clear out the old session so the user is prompted to scan the QR code (which gives them the ability to pick the account they want to use).
=> Disconnect previous WalletConnect session on login page

src/components/gateway/WithdrawConfirmed.vue, src/dpos/components/OtherDelegations.vue, src/dpos/components/ValidationDelegations.vue, src/filters.ts, src/locales/en.json, src/locales/es.json, src/locales/ja.json, src/locales/ko.json, src/locales/th.json, src/locales/zh.json, src/views/MobileAccount.vue
Currently when you login as a validator on the dashboard you'll only see the self-delegations in the `Delegations` section of `My Account`:
We need to add another section below that to display delegations to the validator from other users. This new section should just show a summary on first load (X LOOM staked in total, Y LOOM staked at Tier 0, Z LOOM staked at Tier 1 etc.), and there should be a button that displays a list of all the delegations (a table, with columns for delegator, delegation index, amount staked, tier, and unlock time).
=> Add ability to view all delegations on the My Account page when logged in as a validator
